### ISSUE TITLE
Possible bug in Text3DMesh

### ISSUE THREAD

**Issue by alexeykravtsov87** [FXyz/FXyz#138]
Creation of a Text3DMesh with Text containing two consecutive 'A' symbols, e.g. "AA25" leads to an index out of bounds exception. Probably, `polis.removeIf(LineSegment::isHole);` filter inside Text3DHelper class, removes one extra poly corresponding to the last(?) symbol in the string. Subsequently, Text3DMesh.createLetter yields an exception at
`polyMesh.getTransforms().addAll(new Translate(offset.get(ind).x-origin.get(0).x+indLetters.get()*gap.doubleValue(),0,0));`
since the offset list is one element shorter than needed.
I am using fxyz3d-0.5.3, but all other 0.5.x versions reproduce the issue for me. No other letters, neither upper, nor lower case, lead to such behaviour.

**Comment by jperedadnr** [comment]
I can reproduce the issue from the FXyz-Samples:

```
text AA
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:458)
        at org.fxyz3d.core@0.5.4-SNAPSHOT/org.fxyz3d.shapes.primitives.Text3DMesh.lambda$createLetter$6(Text3DMesh.java:336)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.fxyz3d.core@0.5.4-SNAPSHOT/org.fxyz3d.shapes.primitives.Text3DMesh.createLetter(Text3DMesh.java:310)
        at org.fxyz3d.core@0.5.4-SNAPSHOT/org.fxyz3d.shapes.primitives.Text3DMesh.lambda$updateMesh$2(Text3DMesh.java:288)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
        at java.base/java.lang.StringLatin1$CharsSpliterator.forEachRemaining(StringLatin1.java:770)
        at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.fxyz3d.core@0.5.4-SNAPSHOT/org.fxyz3d.shapes.primitives.Text3DMesh.updateMesh(Text3DMesh.java:288)
        at org.fxyz3d.core@0.5.4-SNAPSHOT/org.fxyz3d.shapes.primitives.Text3DMesh$1.invalidated(Text3DMesh.java:133)
        at javafx.base/javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
        at javafx.base/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145)
        at javafx.base/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:50)
        at org.fxyz3d.core@0.5.4-SNAPSHOT/org.fxyz3d.shapes.primitives.Text3DMesh.setText3D(Text3DMesh.java:143)
        at org.fxyz3d.samples@0.5.4-SNAPSHOT/org.fxyz3d.samples.shapes.texturedmeshes.Text3D$6.invalidated(Text3D.java:107)
```

**Comment by jperedadnr** [comment]
The issue comes from the fact that the 'AA' path doesn't have a separation between the two 'A', and in the first call to Text3DHelper with the full string, there are only 3 polygons (one exterior and two holes)  instead of 4 (two exterior and two holes). Using other font like Times New Roman instead of Arial solves the issue, as there is a gap between the two letters.

So this is not an isolated case, it happens with all "connected" fonts.
