### ISSUE TITLE
Text3DMesh does not work for "fT" string

### ISSUE THREAD

**Issue by runiter** [FXyz/FXyz#191]
It's very simple to reproduce this bug. Simply run this one line:

`new Text3DMesh("fT", 0);`

You will get the following exception thrown:

```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:365)
	at java.base/java.util.ArrayList.get(ArrayList.java:428)
	at org.fxyz3d.core@0.6.0/org.fxyz3d.shapes.primitives.Text3DMesh.lambda$createLetter$6(Text3DMesh.java:336)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:782)
	at org.fxyz3d.core@0.6.0/org.fxyz3d.shapes.primitives.Text3DMesh.createLetter(Text3DMesh.java:310)
	at org.fxyz3d.core@0.6.0/org.fxyz3d.shapes.primitives.Text3DMesh.lambda$updateMesh$2(Text3DMesh.java:288)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.lang.StringLatin1$CharsSpliterator.forEachRemaining(StringLatin1.java:919)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at org.fxyz3d.core@0.6.0/org.fxyz3d.shapes.primitives.Text3DMesh.updateMesh(Text3DMesh.java:288)
	at org.fxyz3d.core@0.6.0/org.fxyz3d.shapes.primitives.Text3DMesh.<init>(Text3DMesh.java:126)
	at org.fxyz3d.core@0.6.0/org.fxyz3d.shapes.primitives.Text3DMesh.<init>(Text3DMesh.java:104)
```

**Comment by runiter** [comment]
I tried all the combinations with 2 characters and found this following combos that also throw above exception:

```
fT
fV
fW
fX
fY
KA
```

All other characters combo seem to work fine. Not sure why these specific character combos throw such exception.

**Comment by coderextreme** [comment]
Were you able to get past this?  I am researching 3D Text APIs in Java.

**Comment by runiter** [comment]
No, the issue is still there. I worked around it by adding a space character between forementioned letters. I was hoping the authors of this library would fix it but looks like this repo hasn't been updated in over a year. It might be abandoned!

**Comment by coderextreme** [comment]
The thought of 3D text is pretty attractive.  Do you still use the library, if not, what do you use for 3D text?

thanks

**Comment by runiter** [comment]
yes I still use this library for 3D text. It works for most cases.

**Comment by Birdasaur** [comment]
The library isn't abandoned, we push minor updates about once a year. We respond weekly to questions and help people whenever we can.
Its basically just two of us doing it in our free time so you can imagine how hard it is to drop everything for something like this.

What are your use cases for this approach? Why are you all trying to do 3D text instead of floating 2D labels?

**Comment by runiter** [comment]
I'd prefer using 2D labels but unfortunately they do not mix well with 3D objects. For example I need the text to hide behind 3D objects when I rotate the view as shown below:

![image](https://github.com/user-attachments/assets/87de1c30-bff6-4091-8b52-7f5bcbbea241)

**Comment by coderextreme** [comment]
Here’s an example of an effect I am trying to achieve, albeit in Three.js: https://coderextreme.net/helloworld/

**Comment by Birdasaur** [comment]
It's hard to tell from just a single screenshot but it looks like you might be placing 2D text into the 3D scene which would result in the issue you are seeing. 
The Javafx way is to place labels as an overlay using a StackPane type pattern.
We have an example here:
https://github.com/FXyz/FXyz/blob/master/FXyz-Samples/src/main/java/org/fxyz3d/samples/utilities/FloatingLabels.java

It works by doing a localToScene type transform which is equivalent to the unproject approach. Each text label is mapped to a 3D point in the scene. Each time the camera changes you just call the method that transforms the label position. It includes clipping logic to prevent labels from stretching the scene.

If you want to have some labels above and some behind you can simply add and manage two label layers in your stackpane.

Also if it helps we have a data cube view component ready to go: https://github.com/FXyz/FXyz/blob/master/FXyz-Core/src/main/java/org/fxyz3d/scene/CubeWorld.java

Here is an example where I extended it to support drawing 2D projections in the inner walls:
https://github.com/trinity-xai/Trinity/blob/main/src/main/java/edu/jhuapl/trinity/javafx/javafx3d/ShadowCubeWorld.java

It's complicated due to all the Trinity app specifics and custom Event handling but you should be able to strip out the extra stuff to suit your needs.

**Comment by Birdasaur** [comment]
Here is a video that captures both the floating label effect and extended cube world tool.
https://youtu.be/NXHQY5Fh1Do?feature=shared

**Comment by Birdasaur** [comment]
oh.... when I reread this thread .... are you specifically trying to place 2D labels above and below 3d objects based on the distance from the camera? 
If so the solution I provided won't achieve that unfortunately.

**Comment by runiter** [comment]
Yes StackPane wouldn't work because as you can see in my example above, half my label is visible but the other half is hidden behind the 3D object. It needs real z-buffering.

**Comment by coderextreme** [comment]
LOL, I thought the label was supposed to be behind the 3D object, and in
front of the rear 3D object.

John

**Comment by Birdasaur** [comment]
Ok in that case the other trick is to insert the 2D label into the 3D scene and then "billboard" it.  Its typically used for images and sprites but you can do it for any 2D object. It's essentially the same premise except you are doing a 3D rotation of the object to always face the camera.
We have a sample which demonstrates it (albeit with an ImageView node instead of a Label or Text node) here:
https://github.com/FXyz/FXyz/blob/master/FXyz-Samples/src/main/java/org/fxyz3d/samples/utilities/Billboarding.java

**Comment by Birdasaur** [comment]
Here is an example of the Billboarding sample in action:
![image](https://github.com/user-attachments/assets/e624b5cb-d0af-44e0-a6eb-5bfd21464042)
Again its rigged up for an ImageView but you should be able to adapt that sample for any 2D node type.

**Comment by runiter** [comment]
Are you sure that a 2D label can be counted as part of a 3D zbuffer? My understanding is that only 3D meshes are included in zbuffer computation.

**Comment by Birdasaur** [comment]
well based on the screenshot it's working for an ImageView. Worth trying with a Text or Label node.

**Comment by Birdasaur** [comment]
BTW... I had forgotten this  issue has come up in the past. Duplicate issue here:
https://github.com/FXyz/FXyz/issues/138

In that thread @jperedadnr identified the root cause as actually being derived from the Font selection and suggests the easiest workaround is simply selecting a non-connected font.

**Comment by jperedadnr** [comment]
Yes, that's right. The ligatures between characters are currently not supported by Text3DMesh.

Ideally, if we could spot where those are happening, we could treat them as single character, as `new Text("ft")` should produce the right path here:

https://github.com/FXyz/FXyz/blob/master/FXyz-Core/src/main/java/org/fxyz3d/shapes/primitives/helper/Text3DHelper.java#L74

so the problem is changing the algorithm to take characters and ligatures: 
https://github.com/FXyz/FXyz/blob/master/FXyz-Core/src/main/java/org/fxyz3d/shapes/primitives/Text3DMesh.java#L287C9-L287C29
