### ISSUE TITLE
Error during run of Sampler

### ISSUE THREAD

**Issue by nlisker** [FXyz/FXyz#35]
After running `./gradlew run` the sampler opens, but does not behave properly. Clicking on Spring, for example, throws

```
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/css/converters/EnumConverter
        at jfxtras.internal.scene.control.skin.ListSpinnerSkin.<init>(ListSpinnerSkin.java:146)
        at jfxtras.scene.control.ListSpinner.createDefaultSkin(ListSpinner.java:257)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9515)
        at javafx.graphics/javafx.scene.Node.applyCss(Node.java:9602)
        at javafx.controls/javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1715)
        at javafx.controls/javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:2042)
        at javafx.controls/javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1253)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:590)
        at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2507)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:410)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:409)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.converters.EnumConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 78 more
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/css/converters/EnumConverter
        at jfxtras.internal.scene.control.skin.ListSpinnerSkin.<init>(ListSpinnerSkin.java:146)
        at jfxtras.scene.control.ListSpinner.createDefaultSkin(ListSpinner.java:257)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9515)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:583)
        at javafx.graphics/javafx.scene.Scene.access$3500(Scene.java:173)
        at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2502)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:410)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:409)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.converters.EnumConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 123 more
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/css/converters/EnumConverter
        at jfxtras.internal.scene.control.skin.ListSpinnerSkin.<init>(ListSpinnerSkin.java:146)
        at jfxtras.scene.control.ListSpinner.createDefaultSkin(ListSpinner.java:257)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
        at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9515)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
        at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:583)
        at javafx.graphics/javafx.scene.Scene.access$3500(Scene.java:173)
        at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2502)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:410)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:409)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.converters.EnumConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 123 more
```

Tried with both java 8 and 9.

**Comment by jperedadnr** [comment]
The exception you have posted happens if you try to run the sampler with Java 9. You need to run it with Java 8, and make sure that your JAVA_HOME points to Java 8 when running it.

Anyway, the library should work also with Java 9/10.
