### ISSUE TITLE
Importing dae models fails [3DViewer]

### ISSUE THREAD

**Issue by jperedadnr** [FXyz/FXyz#47]
DAE importer from 3DViewer/OpenJFX

Some cases fail due to wrong smoothing groups (`PolygonMeshView::updateMesh`), with an `ArrayIndexOutOfBoundsException `:

```
ArrayIndexOutOfBoundsException: Array index out of range: 0
        at javafx.base/com.sun.javafx.collections.ObservableIntegerArrayImpl.rangeCheck(ObservableIntegerArrayImpl.java:276)
        at javafx.base/com.sun.javafx.collections.ObservableIntegerArrayImpl.get(ObservableIntegerArrayImpl.java:184)
        at com.javafx.experiments.shape3d.PolygonMeshView.updateMesh(PolygonMeshView.java:359)

```

As a workaround, changing:
`int currentSmoothGroup = pmesh.getFaceSmoothingGroups().get(f);` to `int currentSmoothGroup = f;` lets the model being imported.

Some other cases fail with `NullPointerException` due to missing textures:

```
java.lang.NullPointerException                                                                                                          
        at com.javafx.experiments.importers.dae.DaeImporter$DaeSaxParser.endElement(DaeImporter.java:329)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.
```

**Comment by Birdasaur** [comment]
@jperedadnr What's the deal with this issue? It looks like an issue for the 3DViewer code and not Fxyz?

**Comment by jperedadnr** [comment]
Right, I don't recall now the context of this issue. We have FXyz-importers now from 3DViewer, but we didn't include the DAE importer.
So definitely not an issue here.

**Comment by Birdasaur** [comment]
Do we want a DAE importer ability?

**Comment by jperedadnr** [comment]
The DAE importer is still available [here](https://github.com/openjdk/jfx/blob/master/apps/samples/3DViewer/src/main/java/com/javafx/experiments/importers/dae/DaeImporter.java). Without much effort it could be added to FXyz-Importers, but it will need some tests.

**Comment by Birdasaur** [comment]
So is it worth it? The model importation thing is interesting to me. On one hand if someone else implemented it then why redo it?
But it would be very nice for new developers to have everything in one library.
